version: '3.8'
services:
  api:
    container_name: 'wehost_be_dev'
    image: 'wehost_be_dev'
    environment:
      - NODE_ENV:dev
    command: yarn
    build:
      context: .
      dockerfile: Dockerfile
      target: 'dev'
    env_file:
      - .env
    entrypoint:
      - yarn
      - run
      - 'start:dev'

    ports:
      - 5000:5000
    networks:
      - nesjs-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
